title: Oll Korrect # name of the site
author: Oll Korrect # name of site's author
email:  # email of site's author
url: https://opmashin.github.io/Oll_Korrect # root address of the site
description:  
  An Options exclusive blog.

permalink: /:slug.html

# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please

theme_config:
  appearance: "dark" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
